quickopen-plugin: Use Gio.Settings instead of Pluma.MessageBus.send_sync()
This completely avoids the use of the message bus to get the filebrowser
root directory.

Traceback (most recent call last):
  File "/usr/lib64/pluma/plugins/pythonconsole/console.py", line 357, in __run
    r = eval(command, self.namespace, self.namespace)
  File "<string>", line 1, in <module>
AttributeError: 'MessageBus' object has no attribute 'send_sync'